blank_issues_enabled: true
contact_links:
  - name: ChronoStar Docs
    url: https://chrono-stellar.github.io/ChronoStar
    about: Check the documentation before opening an issue.
  - name: GitHub Discussions
    url: https://github.com/chrono-stellar/ChronoStar/discussions
    about: Ask questions and discuss ideas here.
