blank_issues_enabled: true
contact_links:
  - name: ChronoStar Docs
    url: https://chronostar-protocol.github.io/ChronoStar
    about: Check the documentation before opening an issue.
  - name: GitHub Discussions
    url: https://github.com/Chronostar-Protocol/ChronoStar/discussions
    about: Ask questions and discuss ideas here.
